// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.6.1
// source: proto/robotcontrol.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandState int32

const (
	CommandState_COMMAND_STATE_UNSPECIFIED CommandState = 0
	CommandState_CREATED                   CommandState = 1
	CommandState_SENT                      CommandState = 2
	CommandState_ACKED                     CommandState = 3
	CommandState_EXECUTED                  CommandState = 4
	CommandState_FAILED                    CommandState = 5
)

// Enum value maps for CommandState.
var (
	CommandState_name = map[int32]string{
		0: "COMMAND_STATE_UNSPECIFIED",
		1: "CREATED",
		2: "SENT",
		3: "ACKED",
		4: "EXECUTED",
		5: "FAILED",
	}
	CommandState_value = map[string]int32{
		"COMMAND_STATE_UNSPECIFIED": 0,
		"CREATED":                   1,
		"SENT":                      2,
		"ACKED":                     3,
		"EXECUTED":                  4,
		"FAILED":                    5,
	}
)

func (x CommandState) Enum() *CommandState {
	p := new(CommandState)
	*p = x
	return p
}

func (x CommandState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_robotcontrol_proto_enumTypes[0].Descriptor()
}

func (CommandState) Type() protoreflect.EnumType {
	return &file_proto_robotcontrol_proto_enumTypes[0]
}

func (x CommandState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandState.Descriptor instead.
func (CommandState) EnumDescriptor() ([]byte, []int) {
	return file_proto_robotcontrol_proto_rawDescGZIP(), []int{0}
}

type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	RobotId       string                 `protobuf:"bytes,2,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	CommandId     string                 `protobuf:"bytes,3,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_proto_robotcontrol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robotcontrol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_robotcontrol_proto_rawDescGZIP(), []int{0}
}

func (x *CommandRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CommandRequest) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *CommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	State         CommandState           `protobuf:"varint,3,opt,name=state,proto3,enum=robotcontrol.v1.CommandState" json:"state,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_proto_robotcontrol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robotcontrol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_robotcontrol_proto_rawDescGZIP(), []int{1}
}

func (x *CommandResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CommandResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResponse) GetState() CommandState {
	if x != nil {
		return x.State
	}
	return CommandState_COMMAND_STATE_UNSPECIFIED
}

func (x *CommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TelemetryMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	RobotId         string                 `protobuf:"bytes,2,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,3,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	Data            []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TelemetryMessage) Reset() {
	*x = TelemetryMessage{}
	mi := &file_proto_robotcontrol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryMessage) ProtoMessage() {}

func (x *TelemetryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robotcontrol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryMessage.ProtoReflect.Descriptor instead.
func (*TelemetryMessage) Descriptor() ([]byte, []int) {
	return file_proto_robotcontrol_proto_rawDescGZIP(), []int{2}
}

func (x *TelemetryMessage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TelemetryMessage) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *TelemetryMessage) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *TelemetryMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TelemetryAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryAck) Reset() {
	*x = TelemetryAck{}
	mi := &file_proto_robotcontrol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryAck) ProtoMessage() {}

func (x *TelemetryAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robotcontrol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryAck.ProtoReflect.Descriptor instead.
func (*TelemetryAck) Descriptor() ([]byte, []int) {
	return file_proto_robotcontrol_proto_rawDescGZIP(), []int{3}
}

func (x *TelemetryAck) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TelemetryAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	RobotId       string                 `protobuf:"bytes,2,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_robotcontrol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robotcontrol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_robotcontrol_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Heartbeat) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_proto_robotcontrol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robotcontrol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_proto_robotcontrol_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_robotcontrol_proto protoreflect.FileDescriptor

const file_proto_robotcontrol_proto_rawDesc = "" +
	"\n" +
	"\x18proto/robotcontrol.proto\x12\x0frobotcontrol.v1\"~\n" +
	"\x0eCommandRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x19\n" +
	"\brobot_id\x18\x02 \x01(\tR\arobotId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x03 \x01(\tR\tcommandId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\"\x95\x01\n" +
	"\x0fCommandResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x123\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1d.robotcontrol.v1.CommandStateR\x05state\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x87\x01\n" +
	"\x10TelemetryMessage\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x19\n" +
	"\brobot_id\x18\x02 \x01(\tR\arobotId\x12*\n" +
	"\x11timestamp_unix_ms\x18\x03 \x01(\x03R\x0ftimestampUnixMs\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"D\n" +
	"\fTelemetryAck\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\"@\n" +
	"\tHeartbeat\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x19\n" +
	"\brobot_id\x18\x02 \x01(\tR\arobotId\"\x1e\n" +
	"\fHeartbeatAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok*i\n" +
	"\fCommandState\x12\x1d\n" +
	"\x19COMMAND_STATE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aCREATED\x10\x01\x12\b\n" +
	"\x04SENT\x10\x02\x12\t\n" +
	"\x05ACKED\x10\x03\x12\f\n" +
	"\bEXECUTED\x10\x04\x12\n" +
	"\n" +
	"\x06FAILED\x10\x052h\n" +
	"\x0eCommandService\x12V\n" +
	"\rCommandStream\x12\x1f.robotcontrol.v1.CommandRequest\x1a .robotcontrol.v1.CommandResponse(\x010\x012i\n" +
	"\x10TelemetryService\x12U\n" +
	"\x0fTelemetryStream\x12!.robotcontrol.v1.TelemetryMessage\x1a\x1d.robotcontrol.v1.TelemetryAck(\x012W\n" +
	"\x10HeartbeatService\x12C\n" +
	"\x04Beat\x12\x1a.robotcontrol.v1.Heartbeat\x1a\x1d.robotcontrol.v1.HeartbeatAck(\x01B?Z=github.com/colin-110/fault-tolerant-robot-backend/proto;protob\x06proto3"

var (
	file_proto_robotcontrol_proto_rawDescOnce sync.Once
	file_proto_robotcontrol_proto_rawDescData []byte
)

func file_proto_robotcontrol_proto_rawDescGZIP() []byte {
	file_proto_robotcontrol_proto_rawDescOnce.Do(func() {
		file_proto_robotcontrol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_robotcontrol_proto_rawDesc), len(file_proto_robotcontrol_proto_rawDesc)))
	})
	return file_proto_robotcontrol_proto_rawDescData
}

var file_proto_robotcontrol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_robotcontrol_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_robotcontrol_proto_goTypes = []any{
	(CommandState)(0),        // 0: robotcontrol.v1.CommandState
	(*CommandRequest)(nil),   // 1: robotcontrol.v1.CommandRequest
	(*CommandResponse)(nil),  // 2: robotcontrol.v1.CommandResponse
	(*TelemetryMessage)(nil), // 3: robotcontrol.v1.TelemetryMessage
	(*TelemetryAck)(nil),     // 4: robotcontrol.v1.TelemetryAck
	(*Heartbeat)(nil),        // 5: robotcontrol.v1.Heartbeat
	(*HeartbeatAck)(nil),     // 6: robotcontrol.v1.HeartbeatAck
}
var file_proto_robotcontrol_proto_depIdxs = []int32{
	0, // 0: robotcontrol.v1.CommandResponse.state:type_name -> robotcontrol.v1.CommandState
	1, // 1: robotcontrol.v1.CommandService.CommandStream:input_type -> robotcontrol.v1.CommandRequest
	3, // 2: robotcontrol.v1.TelemetryService.TelemetryStream:input_type -> robotcontrol.v1.TelemetryMessage
	5, // 3: robotcontrol.v1.HeartbeatService.Beat:input_type -> robotcontrol.v1.Heartbeat
	2, // 4: robotcontrol.v1.CommandService.CommandStream:output_type -> robotcontrol.v1.CommandResponse
	4, // 5: robotcontrol.v1.TelemetryService.TelemetryStream:output_type -> robotcontrol.v1.TelemetryAck
	6, // 6: robotcontrol.v1.HeartbeatService.Beat:output_type -> robotcontrol.v1.HeartbeatAck
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_robotcontrol_proto_init() }
func file_proto_robotcontrol_proto_init() {
	if File_proto_robotcontrol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_robotcontrol_proto_rawDesc), len(file_proto_robotcontrol_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_robotcontrol_proto_goTypes,
		DependencyIndexes: file_proto_robotcontrol_proto_depIdxs,
		EnumInfos:         file_proto_robotcontrol_proto_enumTypes,
		MessageInfos:      file_proto_robotcontrol_proto_msgTypes,
	}.Build()
	File_proto_robotcontrol_proto = out.File
	file_proto_robotcontrol_proto_goTypes = nil
	file_proto_robotcontrol_proto_depIdxs = nil
}
